project:
  type: website
  output-dir: _doc
  render: 
    - "*.qmd"
    - "presentaciones/02/index_legacy.qmd"
lang: es


website:
  title: "**MAG 620**"
  favicon: "images/logo_fvis.svg"
  site-url: "https://facilevisual.com"
  page-navigation: true
  back-to-top-navigation: true
  search: true
  navbar:
    pinned: true
    left:
      - href: about.qmd
        text: Sobre
  
  sidebar:
    logo: "images/logo-mag620.png"
    pinned: true
    style: floating
    background: light
    collapse-level: 1
    contents:
      - text: "---"
      - section: "Materiales"
        contents:
          - href: index.qmd
            text: Inicio
          - href: document.qmd
            text: Pesquerías
          - href: document2.qmd
            text: Acuicultura
      - text: "---"
      - section: "Presentaciones"
        contents:
          - href: presentaciones/00/intro.qmd
            text: Introducción
          - href: presentacion01.qmd
            text: Estandar MSC
          - href: presentacion02.qmd
            text: Estandar ASC
      - text: "---"
      - section: "Práctico"
        contents:
          - href: P1.qmd
            text: Principio 1
          - href: P2.qmd
            text: Principio 2
          - href: P3.qmd
            text: Principio 3

  page-footer:
    right: "Este sitio fue construido utilizando [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Juan-Carlos Quiroz"
    background: "#b2d2dd" 
    border: false

format:
  html:
    theme: lumen
    toc: true
    css: styles.css
    lightbox: 
      match: auto
      loop: false

editor: visual

