---
title: "Certificación en pesquerías"
---

## Estándar MSC

El Estándar [MSC](https://www.msc.org/for-business/fisheries){target="_blank"} es una **herramienta de evaluación** comparativa accesible para todas las pesquerías y se puede utilizar sin requerir que la pesquería obtenga la certificación Marine Stewardship Council. El uso del Estándar para medir el progreso de Proyectos de Mejora de Pesquerías (FIP, sigla en Inglés) permite a las empresas de la cadena de suministro tomar decisiones mejor informadas para participar o abastecerse de estos proyectos. Por lo tanto, es importante que los interesados, en este caso los alumnos, comprendan cómo MSC define una pesquería, sus requisitos para la certificación y su metodología de puntuación.

Este curso busca proporcionar una descripción y alcance sobre:

-   el propósito del Estándar de Pesquerías MSC,
-   las Unidad de Evaluación (UoA) y Unidad de Certificación (UoC) para la definición de pesquerías,
-   los tres (3) Principios del Estándar de Pesquerías MSC,
-   los indicadores de comportamiento (IC) evaluados bajo el Estándar de Pesquerías MSC,
-   la evaluación a nivel de principios e IC, y
-   la implicancia de la pre-evaluación MSC.


## Información de soporte
Acá encontraras la documentación básica para implementar el estándar MSC. Estos documentos deben considerarse
como referencia y no constituyen material obligatorio, aunque, serán de soporte para el *ejercicio práctico*
de este módulo.

### Documentos generales
Una base sobre el alcance del estándar MSC. Desde el año 2018, el estándar MSC ha sido actualizado en tres oportunidades, sumando importantes complejidades al proceso de revisión y auditorias.

::: info-box-general
-   [Requerimientos de certificación
    general](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/general-certification-requirements/msc-general-certification-requirements-2.6.pdf){target="_blank"}
-   [Reglas y conductas no
    aceptables](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/msc-rules-on-unacceptable-conduct.pdf){target="_blank"}
-   [Requerimientos de
    elegibilidad](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/msc-labour-eligibility-requirements.pdf){target="_blank"}
-   [Requisitos de elegibilidad para el trabajo durante
    faenas](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/chain-of-custody-supporting-documents/msc-at-sea-labour-eligibility-requirements-reporting-template-v2.0.docx?Status=Master&sfvrsn=2c99352b_5){target="_blank"}
-   [Vocabulario y acrónimos
    MSC](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/chain-of-custody-supporting-documents/msc-msci-vocabulary.pdf?Status=Master&sfvrsn=c4ea6474_65){target="_blank"}
:::

### Estándar de certificación
Corresponde al procedimiento de certificación con las rubricas y estándar que se evalúan. Utilizando formas pre-diseñadas por MSC, los auditores de MSC deben calificar cada uno de los principios en bases al procedimiento indicado en estos estándar. Note que existen diferentes versiones, las que han surgido a medida se adecua el programa MSC.

::: info-box-important
- [Estandar de Certificación V3.1](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/fisheries-program-documents/msc-fisheries-standard-and-guidance-version3.1.pdf?Status=Master&sfvrsn=65e6141e_9){target="_blank"}
- [Estandar de Certificación V3.0](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/fisheries-program-documents/msc-fisheries-standard-v3-0.pdf){target="_blank"}
- [Estandar de Certificación V2.01](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/fisheries-program-documents/msc-fisheries-standard-v2-01.pdf?sfvrsn=8ecb3272_19){target="_blank"}
:::


### Las recetas
El estándar MSC es complejo y requiere directrices al momento de asignar un puntaje durante la evaluación. Estas guías son los pasos frente a los diferentes procedimientos. 

::: info-box-guia
- [Guia para la certificación - V3.1](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/fisheries-program-documents/msc-fisheries-certification-process-version3.1.pdf?Status=Master&sfvrsn=af98fad3_8){target="_blank"}
- [Guia para la certificación - V3.0](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/fisheries-program-documents/msc-fisheries-certification-process-v3.pdf){target="_blank"}
- [Guia para la certificación - V2.3](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/fisheries-program-documents/msc-fisheries-certification-process-v2-3.pdf){target="_blank"}
- [Asignación de herramientas V1.2](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/fisheries-program-documents/msc-fisheries-standard-toolbox-version1.2.pdf?Status=Master&sfvrsn=ff11ed5_6){target="_blank"}
- [Asignación de herramientas V1.1](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/fisheries-program-documents/msc-fisheries-standard-toolbox.pdf){target="_blank"}
- [Disputas y resoluciones](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/fisheries-program-documents/msc-disputes-process_v1.1.pdf){target="_blank"}
- [Programa de transición V2.0](https://www.msc.org/docs/default-source/default-document-library/for-business/program-documents/chain-of-custody-supporting-documents/in-transition-to-msc-(itm)-program-requirements-and-guidance-pilot-v2.pdf?sfvrsn=45eab433_4){target="_blank"}
- [Herramienta de rastreo y asignación de hitos](https://www.msc.org/docs/default-source/default-document-library/for-business/fishery-improvement-tools/msc-benchmarking-and-tracking-tool-(bmt)-v4-0-english.xlsx?sfvrsn=2db7304d_4){target="_blank"}
:::
