---
title: "Certificación en acuicultura"
---

## Estándar ASC

Las normas del Aquaculture Stewardship Council
([ASC](https://asc-aqua.org/the-new-asc-farm-standard/){target="_blank"}) para los productos del mar
cultivados de forma responsable le permiten demostrar a los consumidores que estos productos se han cultivado
de una manera que contribuye a minimizar el impacto social y medioambiental de la acuicultura.

### Etapas

Pasos a seguir para obtener la certificación del Aquaculture Stewardship Council (ASC):

1.  Investigación: Antes de comenzar el proceso de certificación con el Aquaculture Stewardship Council, es
    importante investigar y comprender los estándares y requisitos establecidos por el ASC. Esto incluye
    familiarizarse con los principios y criterios de certificación, así como con el proceso de evaluación.

2.  Evaluación inicial: Una vez que se haya realizado la investigación inicial, se debe realizar una
    evaluación interna de la operación acuícola para identificar posibles áreas de mejora y asegurarse de que
    se cumplen los requisitos mínimos del ASC.

3.  Planificación: Con base en la evaluación inicial, se debe desarrollar un plan detallado que incluya las
    acciones necesarias para cumplir con los estándares del ASC. Esto puede implicar la implementación de
    prácticas sostenibles, la mejora de la gestión ambiental y social, entre otros aspectos.

4.  Implementación: Una vez que se haya establecido un plan de acción, es fundamental implementar las medidas
    necesarias para cumplir con los estándares del ASC. Esto puede implicar cambios en las prácticas de
    cultivo, la adopción de tecnologías sostenibles y la capacitación del personal.

5.  Auditoría y certificación: Una vez que se hayan implementado todas las medidas necesarias, se debe
    programar una auditoría con un organismo de certificación acreditado por el ASC. Durante la auditoría, se
    evaluará el cumplimiento de los estándares del ASC y, si se cumplen todos los requisitos, se otorgará la
    certificación.

6.  Mantenimiento y mejora continua: Obtener la certificación del ASC es un logro significativo, pero es
    importante recordar que la sostenibilidad es un proceso continuo. Es fundamental mantener los estándares
    establecidos y buscar constantemente maneras de mejorar las prácticas acuícolas para garantizar la
    protección del medio ambiente y la sociedad.

Estos son los pasos generales a seguir para obtener la certificación del Aquaculture Stewardship Council. Es
importante recordar que cada operación acuícola es única y puede requerir enfoques específicos para cumplir
con los estándares del ASC. La certificación del ASC es un reconocimiento del compromiso con la sostenibilidad
y la responsabilidad en la acuicultura.


