---
title: "Certificación de pesquerías y acuicultura"
---

Como parte del curso "Métodos e instrumentos para la gestión de recursos acuaticos" (MGR620), esta página
contiene información sobre el módulo **Certificación de pesquerías y acuicultura**, que será impartido por
[Juan-Carlos Quiroz](https://www.facilevisual.com/jcquiroz) en calidad de profesor invitado. Todos los
materiales del curso se publicarán en este sitio.

<br>

## Temario

::: {.callout-note appearance="simple"}
-   El estándar de certificación y la sostenibilidad en pesquerías y acuicultura,

-   Propósito de los Estándar MSC y ASC,

-   Las Unidad de Evaluación (UoA) y Unidad de Certificación (UoC),

-   Los tres (3) Principios del Estándar de Pesquerías MSC,

-   Los cuatro (4) Principios del Estándar de Acuicultura ASC,

-   Los indicadores de comportamiento (IC) evaluados bajo los Estándar, y

-   Los procesos de pre-certificación.
:::

<br>

## Horarios de clases

| Clase     | Lugar   | Horario                           |
|-----------|---------|-----------------------------------|
| Cátedra   | Virtual | 25 Septiembre (17:10 — 20:10 hrs) |
| Ejercicio | Virtual | 02 Octubre (17:10 — 20:10 hrs)    |
| Discusión | Virtual | 09 Octubre (17:10 — 20:10 hrs)    |

<br>
<br>
## Licencia

[![Creative Commons
License](https://licensebuttons.net/l/by-sa/4.0/88x31.png){alt="Creative Commons License"}](https://creativecommons.org/licenses/by-sa/4.0/)\
Este sitio web ha sido construido bajo una licencia [Creative Commons Attribution-ShareAlike 4.0
International](https://creativecommons.org/licenses/by-sa/4.0/). Visite
[aquí](https://github.com/dukestatsciintrods/blob/master/LICENSE.md) para detalles sobre este tipo de
licencia.
